#!/usr/bin/env python3
"""
Extract Riventide's story graph out of the Python game into plain JSON.

The scene data in game/world/world.py is already uniform dicts, so this
imports World and dumps it rather than re-authoring 3,900 lines by hand.
Same for the race/class tables and the modifier registry. Run it again
after any story edit in world.py to regenerate the JSON the browser
build reads.

    python tools/extract_story.py           # -> web-js/story.json

Asset paths are rewritten onto the transcoded web tree that
tools/build_web_assets.py already produces (web/assets, .jpg/.png/.ogg),
so the browser build streams the same files the pygbag build bundled.
"""

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.environ["RIVENTIDE_WEB"] = "1"  # select the web asset tree in assets_config

from game.world.world import World                      # noqa: E402
from game.characters.character_races import RACES        # noqa: E402
from game.characters.character_classes import CLASSES    # noqa: E402
from game.utils.game_state import GameState              # noqa: E402
from game.assets_config import graphics_path             # noqa: E402
from tools.music_map import LOCATION_MUSIC, SCREEN_MUSIC   # noqa: E402

# web/assets is a local build product (not committed); docs/assets is the
# published copy of the same tree, so fall back to it when web/ is absent.
WEB_ASSETS = ROOT / "web" / "assets"
if not any((WEB_ASSETS / "audio" / "music").glob("*.ogg")):
    WEB_ASSETS = ROOT / "docs" / "assets"


def _resolve_background(name):
    """Map a location's "background" key onto a real file under web/assets.

    GraphicsManager keys these as "background_<name>" and stores desktop
    .png paths; the web tree carries .jpg for opaque images and .png for
    the few with alpha. Probe for whatever actually exists and return a
    path relative to the game root, or None so the page can fall back to
    a solid colour rather than a broken image.
    """
    if not name:
        return None
    for ext in (".jpg", ".png"):
        rel = f"graphics/backgrounds/{name}{ext}"
        if (WEB_ASSETS / rel).exists():
            return f"assets/{rel}"
    return None


def _resolve_audio(name, kind="music"):
    if not name:
        return None
    rel = f"audio/{kind}/{name}.ogg"
    return f"assets/{rel}" if (WEB_ASSETS / rel).exists() else None


def _check_music(locations):
    """Fail the build rather than ship a scene with the wrong or no music."""
    on_disk = {p.stem for p in (WEB_ASSETS / "audio" / "music").glob("*.ogg")}
    problems = []
    unmapped = sorted(k for k in locations if k not in LOCATION_MUSIC)
    if unmapped:
        problems.append(f"locations with no entry in tools/music_map.py: {', '.join(unmapped)}")
    stale = sorted(k for k in LOCATION_MUSIC if k not in locations)
    if stale:
        problems.append(f"music_map.py names locations that no longer exist: {', '.join(stale)}")
    named = set(LOCATION_MUSIC.values()) | {v for v in SCREEN_MUSIC.values() if v}
    missing = sorted(named - on_disk)
    if missing:
        problems.append(f"tracks with no .ogg under {WEB_ASSETS}/audio/music: {', '.join(missing)}")
    unused = sorted(on_disk - named)
    if unused:
        problems.append(f"tracks on disk that nothing plays: {', '.join(unused)}")
    theme_misuse = sorted(k for k, v in LOCATION_MUSIC.items()
                          if v == SCREEN_MUSIC["title"] and k != "title_screen")
    if theme_misuse:
        problems.append(f"the title theme is only for the title screen, but is mapped to: "
                        f"{', '.join(theme_misuse)}")
    if problems:
        raise SystemExit("music map is wrong:\n  " + "\n  ".join(problems))


def _story_order(data):
    """Breadth-first from the start, so the map reads in play order."""
    locs, start = data["locations"], data["start"]
    order, first_from, depth = [start], {start: None}, {start: 0}
    for loc_id in order:
        for c in locs[loc_id]["choices"]:
            nxt = c.get("destination")
            if nxt in locs and nxt not in depth:
                depth[nxt] = depth[loc_id] + 1
                first_from[nxt] = loc_id
                order.append(nxt)
    return order, first_from


def _write_music_map(data):
    """Human-readable map of where each track plays, generated from music_map.py."""
    locs = data["locations"]
    order, first_from = _story_order(data)
    unreachable = [k for k in locs if k not in first_from]
    by_track = {}
    for k in order + unreachable:
        by_track.setdefault(locs[k]["musicKey"], []).append(k)

    def track_changes_into(k):
        prev = first_from.get(k)
        return prev is None or locs[prev]["musicKey"] != locs[k]["musicKey"]

    lines = [
        "# Riventide music map (browser build)",
        "",
        "Generated by `tools/extract_story.py` from `tools/music_map.py`. Edit",
        "`music_map.py`, not this file. The build fails if any location is",
        "unmapped, any track is missing, or any track goes unused.",
        "",
        "## Screens",
        "",
        "| Screen | Track |",
        "|---|---|",
        "| Title screen | `main_theme` |",
        "| Character creation | `intro_music` |",
        "| Ending card (\"The Tale Ends\") | keeps the ending scene's track |",
        "",
        "## By track",
        "",
        "| Track | Plays in |",
        "|---|---|",
        f"| `{SCREEN_MUSIC['title']}` | title screen, "
        + ", ".join(f"`{k}`" for k in by_track.pop(SCREEN_MUSIC['title'], [])) + " |",
        f"| `{SCREEN_MUSIC['create']}` | character creation, "
        + ", ".join(f"`{k}`" for k in by_track.pop(SCREEN_MUSIC['create'], [])) + " |",
    ]
    for track in sorted(t for t in by_track if by_track[t]):
        lines.append(f"| `{track}` | " + ", ".join(f"`{k}`" for k in by_track[track]) + " |")
    lines += [
        "",
        "## In story order",
        "",
        "Breadth-first from the start. \"First reached from\" is one way in, not",
        "the only one. **Bold** marks where the track changes on that path.",
        "",
        "| # | Location | Track | First reached from |",
        "|---|---|---|---|",
    ]
    for i, k in enumerate(order, 1):
        t = f"`{locs[k]['musicKey']}`"
        if track_changes_into(k):
            t = f"**{t}**"
        lines.append(f"| {i} | `{k}` | {t} | {('`' + first_from[k] + '`') if first_from[k] else 'start'} |")
    if unreachable:
        lines += ["", "## Not reachable from the start", "",
                  "Mapped anyway, so they have the right music if a path to them is added.", "",
                  "| Location | Track |", "|---|---|"]
        lines += [f"| `{k}` | `{locs[k]['musicKey']}` |" for k in unreachable]
    out = ROOT / "web-js" / "MUSIC_MAP.md"
    out.write_text("\n".join(lines) + "\n")
    return out


def main():
    world = World()

    locations = {}
    for region_id, region in world.regions.items():
        for loc_id, loc in (region.get("locations") or {}).items():
            out = {
                "id": loc_id,
                "region": region_id,
                "name": loc.get("name"),
                "description": loc.get("description"),
                "dialogue": loc.get("dialogue") or [],
                "choices": loc.get("choices") or [],
                "background": _resolve_background(loc.get("background")),
                "backgroundKey": loc.get("background"),
            }
            # Music comes only from tools/music_map.py; see _check_music().
            out["musicKey"] = LOCATION_MUSIC.get(loc_id)
            out["music"] = _resolve_audio(out["musicKey"])
            if loc.get("modifiers"):
                out["modifierText"] = loc["modifiers"]
            locations[loc_id] = out

    _check_music(locations)

    data = {
        "start": world.get_starting_location()["id"]
        if world.get_starting_location() else "eldoria_introduction",
        "locations": locations,
        "regions": {rid: {"id": rid, "name": r.get("name")}
                    for rid, r in world.regions.items()},
        "screenMusic": {k: _resolve_audio(v) for k, v in SCREEN_MUSIC.items()},
        "races": RACES,
        "classes": CLASSES,
        "modifiers": sorted(GameState().player_modifiers.keys()),
    }

    out_dir = ROOT / "web-js"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / "story.json"
    out_path.write_text(json.dumps(data, indent=1, ensure_ascii=False))

    missing_bg = sorted({l["backgroundKey"] for l in locations.values()
                         if l["backgroundKey"] and not l["background"]})
    print(f"wrote {out_path.relative_to(ROOT)}")
    print(f"  locations   {len(locations)}")
    print(f"  choices     {sum(len(l['choices']) for l in locations.values())}")
    print(f"  races       {len(RACES)}   classes {len(CLASSES)}")
    print(f"  modifiers   {len(data['modifiers'])}")
    print(f"  size        {out_path.stat().st_size/1024:.0f} KB")
    tracks = sorted({l["musicKey"] for l in locations.values()})
    print(f"  music       {len(tracks)} tracks across {len(locations)} locations")
    map_path = _write_music_map(data)
    print(f"wrote {map_path.relative_to(ROOT)}")
    if missing_bg:
        print(f"  MISSING backgrounds ({len(missing_bg)}): {', '.join(missing_bg)}")

if __name__ == "__main__":
    main()
